apiVersion: apps/v1
kind: Deployment
metadata:
  name: guess-game-deployment
spec:
  replicas: 1 # Runs 1 copy of your game app
  selector:
    matchLabels:
      app: guess-game
  template:
    metadata:
      labels:
        app: guess-game
    spec:
      containers:
        - name: guess-game-api
          image: guess-game-backend:v1
          imagePullPolicy: Never # Tells K8s to look on your laptop instead of the internet!
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: guess-game-service
spec:
  type: NodePort # Opens a network gateway to your local machine
  selector:
    app: guess-game
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080 # You will access your API at http://localhost:30080